{
  "compatibilityLevel": 1550,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"dimdate\",\"application_countries\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.130.930.0 (24.06)"
      }
    ],
    "culture": "en-AU",
    "cultures": [
      {
        "name": "en-AU",
        "linguisticMetadata": {
          "content": {
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "885001b4-743d-4451-9fa2-9fbd303a1bc9",
        "fromColumn": "ValidFrom",
        "fromTable": "application_countries",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_54798c71-0fa4-4374-b299-13efa2b872bb"
      },
      {
        "name": "cc974eed-0d3f-45a0-ae50-17483970bf4a",
        "fromColumn": "ValidTo",
        "fromTable": "application_countries",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_55cefff0-31ae-4616-91de-26e6a0df05fb"
      }
    ],
    "sourceQueryCulture": "en-AU",
    "tables": [
      {
        "name": "dimdate",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "DateKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "23b9ee08-59aa-4b1a-b5e5-270ea3d9fc48",
            "sourceColumn": "DateKey",
            "summarizeBy": "count"
          },
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5874a37e-df77-43b2-b912-16dc66ff9678",
            "sourceColumn": "Date",
            "summarizeBy": "none"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f154fbb1-5ee7-487c-b10d-29b28ada1594",
            "sourceColumn": "Day",
            "summarizeBy": "none"
          },
          {
            "name": "MonthName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f443bcda-5fc7-40d0-a98d-4fd485857dd1",
            "sourceColumn": "MonthName",
            "summarizeBy": "none"
          },
          {
            "name": "MonthNumber",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "1508f11f-a70c-4866-a2c3-4401de868973",
            "sourceColumn": "MonthNumber",
            "summarizeBy": "sum"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6992c88c-1e57-40d6-86cb-234f5055ca93",
            "sourceColumn": "Year",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "360dd9ff-c2c2-4c5a-b052-754363b5ea3f",
        "partitions": [
          {
            "name": "dimdate",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"e5iwa2majz6udasazzxgctylte-nqxob3gkh4relm3a7nap5mftmq.datawarehouse.fabric.microsoft.com\", \"LH_Raw\"),",
                "    dbo_dimdate = Source{[Schema=\"dbo\",Item=\"dimdate\"]}[Data]",
                "in",
                "    dbo_dimdate"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_97a6e645-4353-49cc-bbf1-1fb88f44e636",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "a75ead56-ae10-4fd9-ac45-506457cca105",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "82d57c90-3285-44bb-9c7e-8bc26420a9dd",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "b1953d8a-cd03-4a6e-afc7-ea509e7a4a88",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "b62e03fc-d6ac-47a4-bb77-14ecd912bf1c",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "4d1a85a5-d292-4d5c-94b8-ef158758f110",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "43d5eb66-dd5c-4ab9-b00a-cdb985cc702f",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "a085a9a8-21da-47d2-989f-18b4b84ec267",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "fad2890f-074d-493a-b286-8853dc6a7fc1",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "ce65dc60-5152-4418-bea6-8ed99ecf027a",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "5d0e3f94-39a7-40b5-8668-c7676e48384c",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "099f77f2-1326-453a-bcb1-8b2cff48f798",
                "ordinal": 3
              }
            ],
            "lineageTag": "ed9f8b1e-7a8d-4602-9235-523fdd26eeaa"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "35688eec-24f9-41f4-b926-7e348eacb2ae",
        "partitions": [
          {
            "name": "DateTableTemplate_97a6e645-4353-49cc-bbf1-1fb88f44e636",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "application_countries",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "CountryID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ecf12d51-733d-414c-983c-55a7254559b1",
            "sourceColumn": "CountryID",
            "summarizeBy": "count"
          },
          {
            "name": "CountryName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d25efc69-98fd-4956-99aa-7c323baf0719",
            "sourceColumn": "CountryName",
            "summarizeBy": "none"
          },
          {
            "name": "FormalName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "686b6a0c-33ec-43fe-b935-c96bd0ccf0a2",
            "sourceColumn": "FormalName",
            "summarizeBy": "none"
          },
          {
            "name": "IsoAlpha3Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0feee1cd-1333-48f7-bd95-38f09cd0ff07",
            "sourceColumn": "IsoAlpha3Code",
            "summarizeBy": "none"
          },
          {
            "name": "IsoNumericCode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "edb98f4d-935a-49e0-b2c1-fca19b70695d",
            "sourceColumn": "IsoNumericCode",
            "summarizeBy": "count"
          },
          {
            "name": "CountryType",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6d5e8ff9-d2fa-46a0-91e7-54e2d01b9c5b",
            "sourceColumn": "CountryType",
            "summarizeBy": "none"
          },
          {
            "name": "LatestRecordedPopulation",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "81c39114-c97d-441e-a182-c09f5ddb1077",
            "sourceColumn": "LatestRecordedPopulation",
            "summarizeBy": "sum"
          },
          {
            "name": "Continent",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "90227144-6cc8-4e77-9b76-54419dd240c3",
            "sourceColumn": "Continent",
            "summarizeBy": "none"
          },
          {
            "name": "Region",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f2e0bafc-22d9-4074-a37f-44b4d097b181",
            "sourceColumn": "Region",
            "summarizeBy": "none"
          },
          {
            "name": "Subregion",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5c1488ce-c6df-46d6-87a0-6e1788ec1b9a",
            "sourceColumn": "Subregion",
            "summarizeBy": "none"
          },
          {
            "name": "LastEditedBy",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a192901b-5676-43b2-aa6b-5b600109723c",
            "sourceColumn": "LastEditedBy",
            "summarizeBy": "sum"
          },
          {
            "name": "ValidFrom",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "5ffec72d-f06c-4ee8-8021-2f8bd157f999",
            "sourceColumn": "ValidFrom",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_54798c71-0fa4-4374-b299-13efa2b872bb"
                },
                "isDefault": true,
                "relationship": "885001b4-743d-4451-9fa2-9fbd303a1bc9"
              }
            ]
          },
          {
            "name": "ValidTo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "3368f057-25c5-4b61-a19c-b0981a5bbb9c",
            "sourceColumn": "ValidTo",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_55cefff0-31ae-4616-91de-26e6a0df05fb"
                },
                "isDefault": true,
                "relationship": "cc974eed-0d3f-45a0-ae50-17483970bf4a"
              }
            ]
          }
        ],
        "lineageTag": "cc2cad7e-429f-4763-a285-aee631c03bd7",
        "partitions": [
          {
            "name": "application_countries",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\Users\\ahelmy\\OneDrive - Insight\\Documents\\Work\\GBCMA\\PoC\\CSVs\\application_countries.csv\"),[Delimiter=\",\", Columns=13, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"CountryID\", Int64.Type}, {\"CountryName\", type text}, {\"FormalName\", type text}, {\"IsoAlpha3Code\", type text}, {\"IsoNumericCode\", Int64.Type}, {\"CountryType\", type text}, {\"LatestRecordedPopulation\", Int64.Type}, {\"Continent\", type text}, {\"Region\", type text}, {\"Subregion\", type text}, {\"LastEditedBy\", Int64.Type}, {\"ValidFrom\", type datetime}, {\"ValidTo\", type datetime}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_54798c71-0fa4-4374-b299-13efa2b872bb",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "1bae0df8-00e9-44f8-983c-51e1845cbf6a",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "8b36a978-debc-4058-bffd-17c720452d94",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "3c26fb08-142d-4e2e-8266-24ad5df3c3fc",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "ee90e001-bd6e-487b-92b3-8d1d43a33666",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "c32fdb72-b8e3-4d2d-a10c-8b591c833bc0",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "228f3b89-9d8e-413f-950a-0146344bca4e",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "344a15ac-f4d8-4048-8e67-d5c2a37168dd",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "b859dc41-3aa7-4b72-9c20-dafa0f26203b",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "185e4a77-11e5-4731-9e63-4a0895d3f18a",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "27d722b8-2a23-4bfc-aa3a-303a17d3720c",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "b4ecafde-cf0e-444c-816b-1924a6b32212",
                "ordinal": 3
              }
            ],
            "lineageTag": "c12ec217-cf38-4157-87e1-42020f17c51a"
          }
        ],
        "isHidden": true,
        "lineageTag": "16d78da6-6aee-4c4d-9d15-401973beceaf",
        "partitions": [
          {
            "name": "LocalDateTable_54798c71-0fa4-4374-b299-13efa2b872bb",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('application_countries'[ValidFrom])), 1, 1), Date(Year(MAX('application_countries'[ValidFrom])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_55cefff0-31ae-4616-91de-26e6a0df05fb",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "eee78959-4a4f-4479-8c34-a9450ddb8654",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "d4d00330-3c3d-44e8-bc09-e8bff297748b",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "4c71f32b-2029-437b-9eac-242ad384a80a",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "e461798f-586e-49ce-ad6c-802d7418578a",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "5de006c6-4174-4f05-ad08-f13cb66b6166",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "d3d736d0-1ff9-49a1-b1e7-ef166f9f1080",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "f5d581dc-8071-4ac6-b640-a709c2c49ae9",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "11b8df40-07fe-4070-ba80-ec354def5d26",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "38439b01-3560-4a5d-ba0d-0cc54a116822",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "321da263-3760-4e7f-9a12-94f9ae936110",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "1514ee5f-ad87-4767-b659-5c39a03956f8",
                "ordinal": 3
              }
            ],
            "lineageTag": "0fc68f54-26d6-473d-b7c2-87fdfa474cd1"
          }
        ],
        "isHidden": true,
        "lineageTag": "69d5bbfa-9529-483e-adb1-8c48f60afdc5",
        "partitions": [
          {
            "name": "LocalDateTable_55cefff0-31ae-4616-91de-26e6a0df05fb",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('application_countries'[ValidTo])), 1, 1), Date(Year(MAX('application_countries'[ValidTo])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      }
    ]
  }
}